version: '3'

tasks:
  generate:
    desc: Generate OpenRouter models
    aliases: [gen]
    cmds:
      - go run cmd/openrouter/main.go

  generate:apipie:
    desc: Generate APIpie models
    aliases: [gen:apipie]
    cmds:
      - go run cmd/apipie/main.go

  lint:
    desc: Run linters
    cmds:
      - golangci-lint run ./...

  lint:fix:
    desc: Run linters and fix issues
    cmds:
      - golangci-lint run --fix ./...

  fmt:
    desc: Format code
    cmds:
      - go fmt ./...

  modernize:
    desc: Modernize code
    cmds:
      - modernize ./...

  install:
    desc: Install catwalk locally
    cmds:
      - go install -v .

  run:
    desc: Run catwalk
    aliases: [default]
    cmds:
      - go run .
