name: deploy production

on:
  push:
    tags:
      - v*.*.*

concurrency:
  group: goreleaser
  cancel-in-progress: true

jobs:
  goreleaser:
    uses: charmbracelet/meta/.github/workflows/goreleaser.yml@main
    with:
      go_version: stable
    secrets:
      docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
      docker_token: ${{ secrets.DOCKERHUB_TOKEN }}
      goreleaser_key: ${{ secrets.GORELEASER_KEY }}
      gh_pat: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  deploy:
    name: Run deploy workflow
    runs-on: ubuntu-latest
    needs: [goreleaser]
    steps:
      - uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Update
          repo: charmbracelet/infra-prod
          ref: main
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          inputs: |
            {
              "app": "catwalk",
              "image": "ghcr.io/charmbracelet/catwalk:${{ github.ref_name }}"
            }
